### ISSUE TITLE
请教个Senparc的问题

### ISSUE THREAD

**Issue by uniquejuedui** [ShyUncle/gTimedTask#1]
看了你的这个回答

`我也遇到了，设置false仍然会执行保存信息，大量的insert加锁操作会导致redis timeout`
`看了下源码是MP中OnExecutingAsync里面调用了获取上下文操作然后默认插入了一条，我现在是override掉这个方法`

我也重写了这个方法，然后还是向redis写数据，并发高就timeout，就困扰了我很长时间，实在是不知道怎么操作

**Comment by ShyUncle** [comment]
这里不适合讨论这个问题。626999821@qq.com @uniquejuedui
